ENT.Base = "base_anim"
ENT.Type = "anim"
ENT.Category 			= "Kliker"
ENT.PrintName			= "Rolling Rock"
ENT.Author			= "Kliker"
ENT.Contact			= ""
ENT.Purpose			= "The drink of Gods!"
ENT.Instructions		= "Throw it at NPCs and it will explode"
ENT.Spawnable			= true
ENT.AdminSpawnable		= true